# Testing http requests with Visual Studio Code REST Client extension

## Items (test resource/endpoints using hard-coded mock data)

### get all items
GET http://localhost:3000/api/items

### get item by id
GET http://localhost:3000/api/items/3

### post a new item
POST http://localhost:3000/api/items
content-type: application/json

{
  "name": "Sitruuna"
}

### modify an existing item (by using item's id as a parameter in url)
PUT http://localhost:3000/api/items/3
content-type: application/json

{
  "name": "new name for this item"
}

### delete an item (by id)
DELETE http://localhost:3000/api/items/3


###########################
## Users resource endpoints

### get all users
GET http://localhost:3000/api/users

### get user by id
GET http://localhost:3000/api/users/3

### create a new user (user registration)
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "mehrani12342",
  "password": "x1123039283453133",
  "email": "xxnn@exampple.ffiifiiiii"
}

### modify an existing user by id
PUT http://localhost:3000/api/users/3
content-type: application/json

{
  "username": "editedname",
  "password": "editedpasswordx",
  "email": "editedmail@example.com"
}

### delete a user (by id)
DELETE http://localhost:3000/api/users/3

### user login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "mehrani12342",
  "password": "x1123039283453133" 
}

### get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcm5hbWUiOiJtZWhyYW5pMTIzNDIiLCJwYXNzd29yZCI6IiQyYiQxMCR4N1FhWjNLeklQT3I3c2x3Wi9oOVF1NUZvS2I5MlJyelcwdGhjQWRQaFFiQjVsT2ZUa0FvYSIsImVtYWlsIjoieHhubkBleGFtcHBsZS5mZmlpZmlpaWlpIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDMtMDRUMTM6MjI6NTMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQxMDk2MjM1LCJleHAiOjE3NDExODI2MzV9.3RlM5EE_m0Me7GrWBema-ptvIOLGbve5H0_kSqIBI1A
### post a new entry
POST http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcm5hbWUiOiJtZWhyYW5pMTIzNDIiLCJwYXNzd29yZCI6IiQyYiQxMCR4N1FhWjNLeklQT3I3c2x3Wi9oOVF1NUZvS2I5MlJyelcwdGhjQWRQaFFiQjVsT2ZUa0FvYSIsImVtYWlsIjoieHhubkBleGFtcHBsZS5mZmlpZmlpaWlpIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDMtMDRUMTM6MjI6NTMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQxMDk2MjM1LCJleHAiOjE3NDExODI2MzV9.3RlM5EE_m0Me7GrWBema-ptvIOLGbve5H0_kSqIBI1A
content-type: application/json

{
  "entry_date": "2025-02-27",
  "blood_sugar": 5.6,
  "insulin_dose": 12,
  "mood": "iloinen",
  "food": "Kaurapuuro, marjoja, pähkinöitä",
  "exercise": "30 min kävely",
  "weight": 60,
  "sleep_hours": 6,
  "notes": "Neuvolakäynti sujui hyvin, vauva kasvaa normaalisti"
}
### Get user's entries
GET http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcm5hbWUiOiJtZWhyYW5pMTIzNDIiLCJwYXNzd29yZCI6IiQyYiQxMCR4N1FhWjNLeklQT3I3c2x3Wi9oOVF1NUZvS2I5MlJyelcwdGhjQWRQaFFiQjVsT2ZUa0FvYSIsImVtYWlsIjoieHhubkBleGFtcHBsZS5mZmlpZmlpaWlpIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDMtMDRUMTM6MjI6NTMuMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzQxMDk2MjM1LCJleHAiOjE3NDExODI2MzV9.3RlM5EE_m0Me7GrWBema-ptvIOLGbve5H0_kSqIBI1A